theme: jekyll-theme-architect

title: [cargotracker]
description: [Demonstration app. For Java EE technologies]

# sidebar links url
links:
  source: https://github.com/javaee/cargotracker
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

